server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://mysql:3306/npo_ai_manager_deploy}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.saori.npo.domain

logging:
  level:
    com.saori.npo.mapper: debug

gemini:
  api:
    key: ${GEMINI_API_KEY:}
    model: ${GEMINI_MODEL:gemini-2.5-flash}
