spring:
  datasource:
    url: jdbc:mysql://localhost:3306/npo_ai_manager?useSSL=false&serverTimezone=Asia/Tokyo&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.saori.npo.domain

logging:
  level:
    com.saori.npo.mapper: debug